%%{init: {'flowchart': {'curve': 'linear'}}}%%
flowchart LR
    %% System Actors
    Guest((Guest))
    User((Student / Alumni))
    Admin((System Admin))

    %% Boundary
    subgraph System [Alumni Management System]
        direction TB
        UC1([Register & Login])
        UC2([Setup & Manage Profile])
        UC3([Search Alumni Network])
        UC4([Create & Interact with Posts])
        UC5([View & Create Events])
        UC6([Direct Messaging])
        UC7([Approve & Manage Users])
    end

    %% Connections
    Guest --- UC1
    
    User --- UC1
    User --- UC2
    User --- UC3
    User --- UC4
    User --- UC5
    User --- UC6
    
    Admin --- UC1
    Admin --- UC7
